repos:
  - repo: https://github.com/python/black
    rev: 21.7b0
    hooks:
      - id: black
        args:
          - --line-length=127
          - --exclude=wandb
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=nd,reacher,thist,ths
